#!/usr/bin/env python3

import argparse
import os
import logging
import sys
import traceback

import resorter.utils
import resorter.actions
import resorter.modules

import resorter.image
import resorter.audio
import resorter.media

import resorter.gpx

VERSION='0.1.0'

def parse_args():
    examples = """
    Example: %(prog)s -f photos copy exif_make/name
    """
    parser = argparse.ArgumentParser(description='File organizer', prog='resort', fromfile_prefix_chars='@', epilog=examples)
    actions = resorter.actions.ACTIONS

    parser.add_argument('ACTION', default='filter', nargs='?',
                        help='action to be executed over input files ({0})'.format(', '.join(actions.keys())))
    parser.add_argument('EXPRESSION', default=['./name'], nargs='*',
                        help='specify the expression to format the destination or a @file name. Default: name'
                        'Use functions to build the expression. Available functions with examples can be listed with `--list-functions -v`')

    parser.add_argument('-f', '--from', dest='input', nargs='?', default='.', #sys.stdin,
                        help='read file names from a directory, a file. Default: stdin')
    parser.add_argument('-r', '--recursive', dest='recursive', action='store_true',
                        help='scan directories recursively')

    parser.add_argument('-if', '--include', metavar='EXPR', dest='include',
                        help=r'expression for the input files to be included')

    parser.add_argument('-S', '--sort', metavar='EXPR', dest='sort',
                        help=r'sort by EXPR. Example: `name`')
    parser.add_argument('-R', '--reverse', dest='reverse', action='store_true',
                        help=r'reverse sort order, if sorting is requested')

    parser.add_argument('-c', '--custom', metavar='SCRIPT', dest='custom', action='append',
                        help=r'custom functions. The SCRIPT name without extension to be used in expressions. '
                             r'The SCRIPT will be provided with the source file path and other parameters via the command line arguments. '
                             r'The SCRIPT should return the new path')

    parser.add_argument('-s', '--silent', dest='silent', action='store_true',
                        help='be silent')
    parser.add_argument('-v', '--verbose', dest='verbose', action='store_true',
                        help='be verbose. Include arguments and examples to the `--list-functions` output')
    parser.add_argument('-g', '--debug', dest='debug', action='store_true',
                        help='print debug messages')

    parser.add_argument('-a', '--ask', dest='ask', action='store_true',
                        help='ask confirmation on each file')
    parser.add_argument('-p', '--stop', dest='stop', action='store_true',
                        help='stop on first failure')
    parser.add_argument('-i', '--ignore', dest='ignore', action='store_true',
                        help='ignore failures')

    parser.add_argument('--dry-run', dest='dry_run', action='store_true',
                        help='don\'t perform actions, only print')

    parser.add_argument('--version', action='version', version='%(prog)s '+VERSION)
    parser.add_argument('--list-functions', dest='list_functions', action='store_true',
                        help='list available functions to use in EXPR. Add `-v` to see the functions arguments and examples')

    return parser.parse_args()

def ask_cli(msg, opts, default=None):
    answer = None

    question = '{0} {1}? [{2}] '.format(msg, '/'.join(opts.keys()), '/'.join(['*'+v[0] if v[0] == default else v[0] for v in opts.values()]) )
    while not [ k for k, v in opts.items() if answer and answer in v ]:
        print(question, file=sys.stderr, end='')
        answer = input()
        if default and not answer:
            answer = default
            print(answer, file=sys.stderr)
            break
    logging.debug(f'answer: {answer}')
    return answer

def main():

    args = parse_args()

    loglevel = logging.CRITICAL
    if args.debug:
        loglevel = logging.WARNING
        if args.verbose:
            loglevel = logging.DEBUG
        if args.silent:
            loglevel = logging.CRITICAL
    logging.basicConfig(
        format='%(levelname)s:%(module)s.%(funcName)s: %(message)s', level=loglevel)
    
    if args.custom:
        resorter.modules.append(args.custom)

    resorter.modules.update()

    if args.list_functions:
        resorter.modules.list_functions(args.verbose)
        return

    logging.debug(f'action "{args.ACTION}"')
    logging.debug(f'expr "{args.EXPRESSION}"')
    logging.debug(f'filter "{args.include}"')

    expressions = []
    for e in args.EXPRESSION:
        if e.startswith('@'):
            with open(e.lstrip('@'), 'r') as f:
                e = ' '.join(f.readlines())
        e = resorter.utils.Expression(e, resorter.modules.FUNCTIONS) 
        expressions.append(e)

    files = resorter.utils.read_filenames(sys.stdin if args.input == '-' else args.input, args.recursive)
    if args.include:
        filter_expr = resorter.utils.Expression(args.include, resorter.modules.FUNCTIONS)
        files = filter(filter_expr.calc, files)
    
    action = resorter.actions.ACTIONS[args.ACTION]['class']

    ask = ask_cli if args.ask else None
    
    action = action(args.dry_run)

    if args.sort is not None:
        sort_expr = resorter.utils.Expression(args.sort, resorter.modules.FUNCTIONS)
        files = sorted(files, key=lambda k: sort_expr.calc(k) or 0, reverse=args.reverse)

    for source in files:
        try:
            d = ''.join(str(e.calc(source)) for e in expressions)
            question = ('dry ' if args.dry_run else '') + f'{args.ACTION}: {source} -> {d}'
            logging.debug(question)
            if ask:
                print(question, file=sys.stderr)
                options = {'Confirm': 'cCyY', 'Ignore': 'iInN', 'Quit': 'qQxX'}
                answer = ask('', options , 'c')
                if answer in options['Ignore']:
                    continue
                elif answer in options['Quit']:
                    break
            elif args.verbose:
                print(question, file=sys.stderr)
            action.act(source, d)
        except resorter.utils.FuncError as e:
            logging.error(f'Exception: {e}')
            if loglevel == logging.DEBUG:
                traceback.print_tb(sys.exc_info()[2])
            func = e.funcb
            args.silent or print(f"Error in function '{func.name}{func.args}: {e.exc}'.\nHelp: {func.help}\n", file=sys.stderr)
            if args.ignore:
                args.silent or print(e, file=sys.stderr)
            elif args.stop or ask_cli(f'Could not {args.ACTION} {source}.',
                    {'Quit': 'qQ', 'Ignore': 'iI'}, 'i') in 'qQ':
                break

        except Exception as e:
            logging.error(f'Exception: {e}')
            if loglevel == logging.DEBUG:
                traceback.print_tb(sys.exc_info()[2])
            if args.ignore:
                args.silent or print(e, file=sys.stderr)
            elif args.stop or ask_cli(f'Could not {args.ACTION} {source}: {e!r}',
                    {'Quit': 'qQ', 'Ignore': 'iI'}, 'i') in 'qQ':
                break

    action.finalize()
    return 0

try:
    exit(main())
except KeyboardInterrupt:
    logging.warning('Keyboard interrupt')
    exit(-1)


